spring.application.name=banco2026v
server.port=8080

# Perfil activo por defecto
spring.profiles.active=dev

# Configuración general
logging.level.org.springframework=INFO

spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json
